project: 
  type: book
  output-dir: _book
  
book:
  title: "SWFSC Genetics Lab"
  author: "Amy Frey"
  date: last-modified 
  description: "This is a living lab document for the Marine Mammal and Marine Turtle Genetics Programs at Southwest Fisheries Science Center" 
  
  page-footer:
    left: |
      <a href="https://www.fisheries.noaa.gov/about/marine-mammal-and-turtle-division-southwest-fisheries-science-center">SWFSC Marine Mammal and Turtle Division</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://amyfrey.github.io/SWFSC-Genetics_Lab/
  repo-url: https://github.com/amyfrey/SWFSC-Genetics_Lab
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - 01-current-projects.qmd
    - 02-mmtd-archive.qmd
    - 03-communication.qmd
    - 04-standard-operating-procedures.qmd
    - 05-analysis-protocols.qmd
    - 06-onboarding.qmd
   # - 07-funding.qmd
    #- 08-standard-operating-procedures.qmd
    #- 09-academics.qmd
    #- 10-courses.qmd
    #- 11-computing.qmd
 #   - 12-umassd-resources.qmd
#    - 13-smast-resources.qmd
#    - 14-other-faylab-resources.qmd  


# not sure what the following line does; those files are present
bibliography: [references.bib, book.bib]

