# Welcome!

<br> This a living lab document for the Marine Mammal and Marine Turtle Genetics Groups.\
The Marine Mammal & Turtle Division of the NMFS Southwest Fisheries Science Center (SWFSC) conducts research on marine mammals and sea turtles to monitor trends in abundance and provide management advice to domestic and international bodies.

This lab resource is intended to provide an overview for lab members and others about how we do our work, and our expectations for our team. It is also a space to document institutional knowledge and for important information about procedures and available resources.

<br>

The content for this book was developed as part of our group's participation in the [Openscapes Champions program](https://openscapes.org).\
We are extremely grateful to and acknowledge [Dr. Julia Stewart Lowndes](https://twitter.com/juliesquid)' role in helping shape how our lab both works and how we articulate our identity. 🙏\
Thanks also to [TheFayLab](http://www.smast.umassd.edu/lab_fay/) and [Stefanie Butland](https://twitter.com/StefanieButland) for the tutorial and for being willing to share their lab-manual template on Quarto. 🙌\
