
# Procedure to Make 1x Low Tris-EDTA (TE) Buffer pH 7.5 (from solution) GE-035.00 {.unnumbered}
SOP IDENTIFIER:	GE-035.00\
ORIGINAL SOP DATE:	7/20/2023\
NUMBER OF PAGES IN SOP:	3\
REVISION NUMBER:	00\
REVISION DATE:	N/A\
WRITTEN BY:	Erin LaCasella	7/20/2023\
REVIEWED BY:	Amy Frey	\
APPROVED BY:	Victoria Pease \
EFFECTIVE DATE:	\
 
**Scope and Purpose:**
To make 1X Low TE buffer for DNA storage. TE buffer solubilizes DNA or RNA for storage and protects from degradation and has a lower salt content. Ethylenediaminetetraacetic Acid (EDTA) chelates metal ions (e.g. Mg 2+) which normally cause degradation.

**Summary of Method: **
Buffer is made by combining pre-made solutions of: 1M Tris-HCl (pH 7.5) and 0.5 M Ethylenediaminetetraacetic Acid (EDTA, pH 8.0).

**Health and Safety Warnings:**\
•	This procedure uses chemicals that may be harmful.  Please read Appendix A before performing this protocol.\
•	Wear gloves, lab coat, closed-toe shoes and safety glasses.\

**Quality Control:**\
•	Store in the refrigerator in a tightly closed container\
•	Perform procedure in general lab\

**Equipment and Supplies:**\
1.	250 mL (or 500 mL) Graduated cylinder\
2.	250 mL (or 500 mL) orange screw cap bottle\
3.	Tris-HCl (Invitrogen Ultrapure 1M Tris-HCl pH 7.5)\
4.	EDTA (Invitrogen Ultrapure 0.5M EDTA, pH8.0)\
5.	MilliQ water (or Invitrogen Ultrapure water)\

**Procedures:**
To make 250 mL, combine reagents in a graduated cylinder:\
1.	Add 2.5 mL of 1M Tris-HCl pH 7.5 (pre-made solution)\
      2.   Add 50 uL of 0.5M EDTA pH 8.0 (pre-made solution)\
3.	Add MilliQ water to total 250 mL \
4.	Pour into the orange screw cap bottle\
5.	Mix the solution by carefully inverting the bottle a few times\
6.	Label the bottle and store in refrigerator\

**Waste Management:**
If there are questions on handling chemicals contact the Safety Officer or Lab Manager. Spills, cuts or other accidents should be reported to the Safety Officer and Lab Manager.

**References:**
For SDS information, go to C:\\Users\ljuser\Desktop\MMTD Genetics SDS (see Lab Manager for designated computers).

**Hazardous substance information: **\
<https://epa.gov/ceppo/pubs/title3.pdf>
 
**Appendix A: Chemical Health and Safety Warnings**

**TE Buffer (Tris and EDTA)**\
Can cause damage to the kidneys, central nervous system and reproductive systems.  It can cause skin, eye, digestive tract and respiratory irritation as well. \
[First Aid]{.underline} \
*Eye contact:* flush eyes with water for at least 15 minutes while occasionally opening and closing eyelids.  Seek medical attention immediately. \
*Skin:* wash skin with lots of water and soap.  Wash clothes before wearing them again and see a doctor if further skin irritation occurs.\
*Ingestion:* drink 2-4 cups of milk if conscious and then seek medical aid.\
*Inhalation:* seek fresh air immediately.  If user has trouble breathing, give him/her oxygen and seek medical attention.\
**Tris**\
Irritating to the eyes, skin, mucous membrane and the upper respiratory tract.  Signs and symptoms of exposure include watery eyes and rough, red skin. When inhaled, it can cause irritation, cough and shortness of breath.  Exposing the substance into excessive heat may cause thermal decomposition and produce toxic fumes like carbon monoxide. It is incompatible with oxidizing materials. \
[First Aid]{.underline}\
*Eyes:* flush with water for 15 minutes.\
*Skin:* flush with water and wash thoroughly with soap and water.  Remove contaminated clothing. If irritation persists, seek medical advice.\
*Inhalation:* move victim to fresh air.\
*Ingestion:* drink water and seek immediate medical attention.\
**EDTA**\
Irritating to the eyes, skin and the mucous membrane of the upper respiratory tract.  It is flammable –do not expose to heat or flame.  Flame caused by EDTA can be extinguished by carbon dioxide, foam, water or dry chemicals. EDTA has emerged as a persistent organic pollutant.\
[First Aid]{.underline}\
*Skin:* rinse with water immediately\
*Eye contact:* wash with water immediately and contact a physician right away.\

