# Standard Operating Procedures (SOP's) {.unnumbered}

A comprehensive list of Standard Operating Procedures (i.e. protocols) for various lab procedures can be found below. The SOP's are organized by lab or area of focus.

## General Lab SOP's ##

**GE-001.00** Procedure to Make 25X TBE\

**GE-002.00** Procedure to Make ProteinaseK (PK) Buffer\

**GE-003.00** Procedure to Make TEQ Buffer\

**GE-004.00** Procedure to Prepare SDS solution (10%,20%)\

**GE-005.00** Procedure to Prepare Lysis Buffer Ia for Lysis Buffer Blood Extraction\

**GE-006.00** Procedure to Prepare Lysis Buffer II for Lysis Buffer Blood Extraction\

**GE-007.00** Procedure to make 1x Tris-EDTA (TE) Buffer\

**GE-008.00** Procedure to make 5M NaCl solution\

**GE-009.00** Procedure to make Lysis Buffer for Hoess and Paabo DNEasy Extraction Protocol\

**GE-010.00** Procedure to make L2 Buffer\

**GE-011.00** Procedure to make LiCl Extraction Buffer\

**GE-012.00** Procedure to prepare STE Buffer\

**GE-013.00** Procedure to make a 5M LiCl solution\

**GE-014.00** Procedure to prepare Chloroform-Isoamyl\

**GE-015.00** Procedure to make 3M NaOac pH5.2\

**GE-016.00** Procedure to prepare Magic Buffer\

**GE-017.01** Procedure to make 20% Dimethylsulfoxide (DMSO) Salt saturated solution\

**GE-018.00** Procedure to make 5X orange G\

**GE-019.00** Procedure to prepare a 0.5M EDTA pH8.0 solution\

**GE-020.00** Procedure to make 1M Tris\

**GE-021.00** Procedure to make 1X PBS Buffer\

**GE-022.00** Procedure to make saturated NaCl solution\

**GE-023.00** Procedure to operate the pH meter\

**GE-024.00** Procedure to autoclave liquids and solids\

**GE-025.00** How to keep a lab notebook\

**GE-026.00** Lab Rules and Etiquette\

**GE-027.00** Procedure to print extraction dot labels\

**GE-028.00** Procedure to print dot labels for aliquots\

**GE-029.00** Procedure to print chemical labels for reagent bottles\

**GE-032.00** Procedure to make 1% DTT solution\

**GE-033.00** Procedure to make Lifton's Buffer\

**GE-034 .00** Procedure to make Hybridization Buffer\

**GE-035.00** Procedure to Make 1x Low Tris-EDTA (TE) Buffer pH 7.5 (from solution)\


## Pre-PCR Lab SOP's ##

**PR-003.00** Extraction of DNA from Tissue Using Sodium Chloride (NaCl)\

**PR-005.00** Extraction of DNA from nucleated blood using lysis buffers\

**PR-006.00** Extraction of DNA from tissue using DNEasy kit\

**PR-010.01** Preparation of Extraction Grid\

**PR-011.00** Extraction Evaluation\

**PR-012.00** Quantification of DNA using Nanodrop® ND-1000 Spectrophotometer\

**PR-014.00** Procedure to prepare and aliquot Proteinase K\

**PR-015.00** Procedure to aliquot Taq polymerase\

**PR-016.00** Procedure to prepare and aliquot deoxynucleotide triphosphates (dNTPs) mix (100mM)\

**PR-017.00** Procedure to prepare a Polymerase Chain Reaction (PCR)\

**PR-019.00** Quantifying DNA using the Perkin Elmer® VictorX3(tm) 2030 Multilabel Reader\

**PR-022.00** Procedure to Determine Gender of Cetaceans using real time Polymerase Chain Reaction (q-PCR)\

**PR-026.00** Procedure to Quantify Nuclear DNA using BMI1 Primers and the Strategene MXP qPCR Machines\

**PR-027.01** Procedure to Quantify Mitochondrial DNA using CET12s Primers and the Strategene MXP qPCR Machines\

**PR-028.00** Procedure to Determine Gender of Pinnipeds and Cetaceans Using Polymerase Chain Reaction (PCR)_SR\

**PR-029.00** Procedure to prepare a multiplex(PCR)\

**PR-030.00** Quantifying DNA using Quant-iT ™ dsDNA Assay Kits and the Perkin Elmer® VictorX3(tm) 2030 Multilabel Reader\

**PR-031.00** Procedure To Transfer DNA From 1.7ml tubes to 1.1ml  micronic tubes\

**PR-033.00** Procedure to Determine Gender of Pinnipeds using real time Polymerase Chain Reaction (q-PCR)\

**PR-034.00**_Procedure to extract DNA using NucleoMag Manual Bead Protocol\

**PR-035.00** Procedure to extract DNA from tissue using the Machery-Nagel NucleoMag® Tissue kit\

**PR-036.00** Procedure to Resuspend and Dilute Primers\

**PR-038.00** Procedure to Quantify using the Qubit\

**PR-039.00** Procedure to Extract DNA from Fecal Material using QIAamp Fast DNA Mini Stool Kit\

**PR-040.01** Procedure to prepare ROX for qPCR runs\

## Post-PCR Lab SOP's ##


**PO-001.00** Procedure to Prepare Agarose Gel for Electrophoresis\

**PO-002.00** Performing Agarose Gel Electrophoresis\

**PO-003.00** Procedure to Prepare1X TBE\

**PO-004.00** Procedure to set up microsatellite plate on the ABI 3730\

**PO-006.00** Procedure for purifying PCR product with the QIAquick PCR purification kit\

**PO-005.00** Procedure to prepare an Amplifluor SNPs Genotyping reaction\

**PO-007.00** Procedure for Purifying PCR Product with Exo-SAP\

**PO-008.00** Procedure for preparing a Cycle Sequence reaction\

**PO-009.00** Purification of DNA Sequencing Reactions Using BigDye XTerminator\

**PO-010.00** Procedure to prepare and aliquot ExoSAP\

**PO-011.00** Procedure to prepare and aliquot BigDye v3.1 with 5X BigDye Buffer\

**PO-012.00** Procedure to Aliquot HiDi formamide\

**PO-013.00** Procedure to use the Zymoclean Gel DNA Recovery Kit\

**PO-014.00** Procedure for Agarose-based Sex Determination\

**PO-017.00** Operation and Maintenance of the ABI 3730 Genetic Analyzer\

**PO-019.00** Procedure to make serial dilutions from pre-made Standard Clones for CET12s and BMI assays\

**PO-020.00** Procedure to purify DNA Sequencing reactions using CleanSEQ\

**PO-021.01** Procedure to Quantify using the Qubit and Qubit Flex\



## Next Generation Sequencing (NGS) SOP's ##


**NG-001.02** Procedure to prepare Indexed libraries for sequencing on Illumina Genome Analyzers using Agilent capture array hybridization or Shotgun methods \

**NG-002.01** Procedure to archive Next Generation Sequencing (NGS) fastq data files_\

**NG-005.00** Procedure to clean the MiSeq\

**NG-007.00** Procedure to Prepare GtSEQ NGS Library\

**NG-008.00** Procedure for Epigenetics for Aging using Targeted Amplicons\

**NG-010.00** Procedure to Quanitfy Illumina adapted PCR product using Kapa standards\

